spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://postgres:5432/catalog
    username: catalog
    password: catalog

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/catalog
    username: catalog
    password: catalog

  liquibase:
    enabled: true
    url: jdbc:postgresql://postgres:5432/catalog
    user: catalog
    password: catalog
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: INFO
    liquibase: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
